//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Newton.cpp
//  @ Date : 19.03.2018
//  @ Author :
//
//


#include "Newton.h"

double Newton::getRes() {
    return res;
}

Newton::Newton(int x, int y) {
    res = silnia(x)/(silnia(y)*silnia(x-y));
}
int Newton::silnia(int x) {
    int res=x;
    for(int i=1;i<x;i++){
        res*=i;
    }
    return res;
}

