//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SchematBernouliego.cpp
//  @ Date : 19.03.2018
//  @ Author :
//
//

#include<math.h>
#include "SchematBernouliego.h"
#include<iostream>

double SchematBernouliego::useSchemat(int k, double p, int n) {
    q=1-p;
    WzorNewt = new Newton(n,k);
    return (WzorNewt->getRes())*pow(p,k)*pow(q,n-k);
}

SchematBernouliego::SchematBernouliego() {
}
