//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Jamnik.cpp
//  @ Date : 26.02.2018
//  @ Author : 
//
//


#include "Jamnik.h"

using namespace std;

float Jamnik::noon(float y) {
    return y;
}

int Jamnik::pij(int x) {

}

