//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pies.h
//  @ Date : 26.02.2018
//  @ Author : 
//
//


#if !defined(_PIES_H)
#define _PIES_H

#include "Ssak.h"

class Pies : public Ssak {
public:
	int pij(int x);
protected:
	int age;
	int beer(int h);
};

#endif  //_PIES_H
