//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pies.cpp
//  @ Date : 26.02.2018
//  @ Author : 
//
//


#include "Pies.h"

using namespace std;

int Pies::pij(int x) {

}

int Pies::beer(int h) {

}

