//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.cpp
//  @ Date : 26.02.2018
//  @ Author : 
//
//


#include "Ssak.h"

int Ssak::nothing_to_do() {
	return 0;
}

int Ssak::pij(int x) {
    return x;
}

void Ssak::krzycz(double t) {

}

