//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.h
//  @ Date : 26.02.2018
//  @ Author : 
//
//


#if !defined(_SSAK_H)
#define _SSAK_H

#include "Zwierze.h"

using namespace std;

class Ssak : public Zwierze {
public:
	double y;
	int nothing_to_do();
	int pij(int x);
private:
	void krzycz(double t);
};

#endif  //_SSAK_H
