//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TBook.cpp
//  @ Date : 05.03.2018
//  @ Author : 
//
//


#include "TBook.h"

TBook::TBook() {

}

TBook::~TBook() {
cout<<"Usuwam ksazke"<<"\n";
}

void TBook::setTitle(string title) {
this->bookTitle=title;
}

string TBook::getTitle() {
return bookTitle;
}

void TBook::setShelfMark(string mark) {
this->shelfMark=mark;
}

string TBook::getShelfMark() {
return shelfMark;
}

