//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TLibrary.cpp
//  @ Date : 05.03.2018
//  @ Author : 
//
//


#include "TLibrary.h"

TLibrary::TLibrary(string lbName) {
this->book=new TBook;
this->libraryName=lbName;
}

TLibrary::~TLibrary() {
delete book;
cout<<"Usuwam biblioteke"<<"\n";
}

void TLibrary::printData() {

cout<<"Library Name - "<<this->libraryName<<"\n";
cout<<"Title - "<<this->book->getTitle()<<"\n";
cout<<"Shelf Mark - "<<this->book->getShelfMark()<<"\n";
}

void TLibrary::setData(string title, string mark) {
this->book->setTitle(title);
this->book->setShelfMark(mark);
}

