//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TLibrary.h
//  @ Date : 05.03.2018
//  @ Author : 
//
//


#if !defined(_TLIBRARY_H)
#define _TLIBRARY_H
#include<TBook.h>
#include<iostream>
#include<string>

using namespace std;

class TLibrary {
public:
	TLibrary(string lbName);
	~TLibrary();
	void printData();
	void setData(string title, string mark);
private:
	TBook* book;
	string libraryName;
};

#endif  //_TLIBRARY_H
