//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TUniversity.cpp
//  @ Date : 05.03.2018
//  @ Author : 
//
//


#include "TUniversity.h"
using namespace std;


TUniversity::TUniversity(string univName) {
name=univName;
students = new TStudent[100];
rozm=0;
}

void TUniversity::printData() {
    for(int i=0;i<rozm;i++){
        cout<<students[i].getName()<<" "<<students[i].getAge()<<endl;
    }
}

void TUniversity::setData(string name, int age) {    
    students[rozm].setName(name);
    students[rozm].setAge(age);
    rozm++;
}

